apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: init-pipeline-github
  namespace: tekton-pipelines
spec:
  description: >-
    This task will init the pipeline from a github repository
  workspaces:
    - name: git-environment
  params:
    - name: pipelineUrl
      type: string
      description: the pipeline url
    - name: gitBranchName
      type: string
      description: the branch name
    - name: repoOrg
      type: string
      description: the github organization name
    - name: repoName
      type: string
      description: the github repo name
    - name: buildId
      type: string
      description: build id (suffix of the pipelineruns name) to filter
    - name: logLevel
      type: string
      description: the level of log (debug or info)
      default: info
    - name: slackChannel
      type: string
      description: the slack channel
      default: "tekton"
    - name: namespace
      type: string
      description: namespace of tekton pipelines
      default: tekton-pipelines
  resources:
    inputs:
      - name: git-input
        type: git
  steps:
    - name: kill-redundant-pipelines
      image: comworkio/tekton-utils-kill-redundant-pipelines:latest
      env:
        - name: GIT_BRANCH
          value: $(params.gitBranchName)
        - name: PROJECT_NAME
          value: $(params.repoName)
        - name: BUILD_ID
          value: $(params.buildId)
        - name: LOG_LEVEL
          value: $(params.logLevel)
        - name: TEKTON_NAMESPACE
          value: $(params.namespace)
        - name: KUBE_ENV
          valueFrom:
            secretKeyRef:
              name: kube-auth
              key: env
        - name: KUBE_URL
          valueFrom:
            secretKeyRef:
              name: kube-auth
              key: url
        - name: KUBE_TOKEN
          valueFrom:
            secretKeyRef:
              name: kube-auth
              key: token
      command: ["/kill-redundant-pipelines.sh"]
    - name: init-env
      env:
        - name: LOG_LEVEL
          value: $(params.logLevel)
        - name: SLACK_CHANNEL
          value: $(params.slackChannel)
        - name: PIPELINE_URL
          value: $(params.pipelineUrl)
        - name: GIT_BRANCH
          value: $(params.gitBranchName)
        - name: REPO_NAME
          value: $(params.repoName)
        - name: REPO_ORG
          value: $(params.repoOrg)
        - name: TEKTON_WORKSPACE_PATH
          value: $(workspaces.git-environment.path)
        - name: GITHUBTOKEN
          valueFrom:
            secretKeyRef:
              name: github-access
              key: password
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-token
              key: token
      image: comworkio/tekton-utils-init-pipeline-github:latest
      workingDir: /workspace/git-input
      command: ["/init-pipeline.sh"]
