version: "3.3"

services:
  yaml-merge:
    image: comworkio/tekton-utils-yaml-merge
    build:
      context: yaml-merge
      dockerfile: Dockerfile
  yaml-patch:
    image: comworkio/tekton-utils-yaml-patch
    build:
      context: yaml-patch
      dockerfile: Dockerfile
  git-sync-branches:
    image: comworkio/tekton-utils-git-sync-branches
    build:
      context: git-sync-branches
      dockerfile: Dockerfile
  git-fetch-sources:
    image: comworkio/tekton-utils-git-fetch-sources
    build:
      context: .
      dockerfile: git-fetch-sources/Dockerfile
  git-push-changes:
    image: comworkio/tekton-utils-git-push-changes
    build:
      context: git-push-changes
      dockerfile: Dockerfile
  github-search-pr:
    image: comworkio/tekton-utils-github-search-pr
    build:
      context: .
      dockerfile: github-search-pr/Dockerfile
  github-open-pr:
    image: comworkio/tekton-utils-github-open-pr
    build:
      context: .
      dockerfile: github-open-pr/Dockerfile
  github-bump-pr:
    image: comworkio/tekton-utils-github-bump-pr
    build:
      context: .
      dockerfile: github-bump-pr/Dockerfile
  github-set-status:
    image: comworkio/tekton-utils-github-set-status
    build:
      context: .
      dockerfile: github-set-status/Dockerfile
  github-add-comment:
    image: comworkio/tekton-utils-github-add-comment
    build:
      context: .
      dockerfile: github-add-comment/Dockerfile
  github-webhook:
    image: comworkio/tekton-utils-github-webhook
    build:
      context: github-webhook
      dockerfile: Dockerfile
  generate-certificate:
    image: comworkio/tekton-utils-generate-certificate
    build:
      context: generate-certificate
      dockerfile: Dockerfile
  kubect-secret-cert:
    image: comworkio/tekton-utils-kubect-secret-cert
    build:
      context: kubect-secret-cert
      dockerfile: Dockerfile
  create-ingress:
    image: comworkio/tekton-utils-create-ingress
    build:
      context: create-ingress
      dockerfile: Dockerfile
  slack-sender:
    image: comworkio/tekton-utils-slack-sender
    build:
      context: slack-sender
      dockerfile: Dockerfile
  slack-result-sender:
    image: comworkio/tekton-utils-slack-result-sender
    build:
      context: .
      dockerfile: slack-result-sender/Dockerfile
  state-success:
    image: comworkio/tekton-utils-state-success
    build:
      context: .
      dockerfile: state-success/Dockerfile
  kaniko-build:
    image: comworkio/tekton-utils-kaniko-build
    build:
      target: image_builder
      context: .
      dockerfile: kaniko-build/Dockerfile
      args: 
        - KANIKO_TAG=v1.5.1
  php-checks-7-4:
    image: comworkio/tekton-utils-php-checks-7-4
    build: 
      context: php-checks
      dockerfile: Dockerfile
      target: php_checks
      args:
        PHP_VERSION: 7.4
        COMPOSER_VERSION: 1.10.13
  yarn-checks-node12:
    image: comworkio/tekton-utils-yarn-checks-node12
    build:
      context: yarn-checks
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 12
  yarn-checks-node14:
    image: comworkio/tekton-utils-yarn-checks-node14
    build:
      context: yarn-checks
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 14
  kubectl:
    image: comworkio/tekton-utils-kubectl
    build:
      context: kubectl
      dockerfile: Dockerfile
  init-pipeline:
    image: comworkio/tekton-utils-init-pipeline
    build:
      context: .
      dockerfile: init-pipeline/Dockerfile
  init-pipeline-github:
    image: comworkio/tekton-utils-init-pipeline-github
    build:
      context: .
      dockerfile: init-pipeline-github/Dockerfile
  kill-redundant-pipelines:
    image: comworkio/tekton-utils-kill-redundant-pipelines
    build:
      context: .
      dockerfile: kill-redundant-pipelines/Dockerfile
  destroy-pvc:
    image: comworkio/tekton-utils-destroy-pvc
    build:
      context: .
      dockerfile: destroy-pvc/Dockerfile
  destroy-pods:
    image: comworkio/tekton-utils-destroy-pods
    build:
      context: .
      dockerfile: destroy-pods/Dockerfile
  clean-old-pipelines:
    image: comworkio/tekton-utils-clean-old-pipelines
    build:
      context: .
      dockerfile: clean-old-pipelines/Dockerfile
  end-pipeline-github:
    image: comworkio/tekton-utils-end-pipeline-github
    build:
      context: .
      dockerfile: end-pipeline-github/Dockerfile
