version: "3.3"

services:
  git-fetch-sources:
    image: comworkio/tekton-utils-git-fetch-sources
    build:
      context: git-fetch-sources
      dockerfile: Dockerfile
  github-search-pr:
    image: comworkio/tekton-utils-github-search-pr
    build:
      context: github-search-pr
      dockerfile: Dockerfile
  github-set-status:
    image: comworkio/tekton-utils-github-set-status
    build:
      context: github-set-status
      dockerfile: Dockerfile
  slack-sender:
    image: comworkio/tekton-utils-slack-sender
    build:
      context: slack-sender
      dockerfile: Dockerfile
