apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: init-pipeline
  namespace: tekton-pipelines
spec:
  description: >-
    This task will init the pipeline from a github repository
  workspaces:
    - name: git-environment
  params:
    - name: pipelineUrl
      type: string
      description: the pipeline url
    - name: gitBranchName
      type: string
      description: the branch name
    - name: repoOrg
      type: string
      description: the github organization name
    - name: repoName
      type: string
      description: the github repo name
    - name: logLevel
      type: string
      description: the level of log (debug or info)
      default: info
    - name: slackChannel
      type: string
      description: the slack channel
      default: "tekton"
  resources:
    inputs:
      - name: git-input
        type: git
  steps:
    - name: init-env
      env:
        - name: LOG_LEVEL
          value: $(params.logLevel)
        - name: SLACK_CHANNEL
          value: $(params.slackChannel)
        - name: PIPELINE_URL
          value: $(params.pipelineUrl)
        - name: GIT_BRANCH
          value: $(params.gitBranchName)
        - name: REPO_NAME
          value: $(params.repoName)
        - name: REPO_ORG
          value: $(params.repoOrg)
        - name: TEKTON_WORKSPACE_PATH
          value: $(workspaces.git-environment.path)
        - name: GITHUBTOKEN
          valueFrom:
            secretKeyRef:
              name: github-access
              key: password
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-token
              key: token
      image: comworkio/tekton-utils-init-pipeline-github:latest
      workingDir: /workspace/git-input
      command: ["/init-pipeline.sh"]
