apiVersion: v1
kind: ConfigMap
metadata:
  name: tekton-clean-old-pipelines-conf
  namespace: tekton-pipelines
data:
  namespace: "tekton-pipelines"
  wait_time: "43200"
  project_prefixes: "(project1|project2)"
  retention_days: "1"
  should_slack: "on"
  slack_username: tekton-clean
  slack_channel: "#tekton"
  slack_avatar: ":tekton:"
  slack_color: "#87CEEB"
  enable_destroy_pvc: enabled
  max_pipelines_keep: "100"
  
