apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-clean-old-pipelines
  namespace: tekton-pipelines
  labels:
    app: tekton-clean-old-pipelines
    app.kubernetes.io/name: tekton-clean-old-pipelines
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-clean-old-pipelines
      app.kubernetes.io/name: tekton-clean-old-pipelines
  template:
    metadata:
      labels:
        app: tekton-clean-old-pipelines
        app.kubernetes.io/name: tekton-clean-old-pipelines
    spec:
      containers:
        - name: tekton-clean-old-jobs
          image: comworkio/tekton-utils-clean-old-pipelines:latest
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: tekton-clean-old-pipelines-conf
                  key: namespace
            - name: PROJECT_PREFIXES
              valueFrom:
                configMapKeyRef:
                  name: tekton-clean-old-pipelines-conf
                  key: project_prefixes
            - name: MAX_PIPELINES_KEEP
              valueFrom:
                configMapKeyRef:
                  name: tekton-clean-old-pipelines-conf
                  key: max_pipelines_keep
            - name: ENABLE_DESTROY_PVC
              valueFrom:
                configMapKeyRef:
                  name: tekton-clean-old-pipelines-conf
                  key: enable_destroy_pvc
            - name: ENABLE_CLEAN_RESOURCES
              valueFrom:
                configMapKeyRef:
                  name: tekton-clean-old-pipelines-conf
                  key: enable_clean_resources
            - name: RETENTION_DAYS
              valueFrom:
                configMapKeyRef:
                  name: tekton-clean-old-pipelines-conf
                  key: retention_days
            - name: WAIT_TIME
              valueFrom:
                configMapKeyRef:
                  name: tekton-clean-old-pipelines-conf
                  key: wait_time
            - name: SHOULD_SLACK
              valueFrom:
                configMapKeyRef:
                  name: tekton-clean-old-pipelines-conf
                  key: should_slack
            - name: SLACK_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: tekton-clean-old-pipelines-conf
                  key: slack_username
            - name: SLACK_EMOJI_AVATAR
              valueFrom:
                configMapKeyRef:
                  name: tekton-clean-old-pipelines-conf
                  key: slack_avatar
            - name: SLACK_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: tekton-clean-old-pipelines-conf
                  key: slack_channel
            - name: SLACK_COLOR
              valueFrom:
                configMapKeyRef:
                  name: tekton-clean-old-pipelines-conf
                  key: slack_color
            - name: KUBE_ENV
              valueFrom:
                secretKeyRef:
                  name: kube-auth
                  key: env
            - name: KUBE_URL
              valueFrom:
                secretKeyRef:
                  name: kube-auth
                  key: url
            - name: KUBE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kube-auth
                  key: token
            - name: SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-token
                  key: token
