apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-pipeline-api
  namespace: tekton-pipelines
  labels:
    app: tekton-pipeline-api
    app.kubernetes.io/name: tekton-pipeline-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-pipeline-api
      app.kubernetes.io/name: tekton-pipeline-api
  template:
    metadata:
      labels:
        app: tekton-pipeline-api
        app.kubernetes.io/name: tekton-pipeline-api
    spec:
      imagePullSecrets: 
        - name: harbor-secret
      containers:
        - name: tekton-pipeline-api
          image: harbor.yyyyyy.io/stable/tekton-pipeline-api:latest
          imagePullPolicy: Always
          env:
            - name: KUBE_ENV
              valueFrom:
                secretKeyRef:
                  name: kube-auth
                  key: env
            - name: KUBE_URL
              valueFrom:
                secretKeyRef:
                  name: kube-auth
                  key: url
            - name: KUBE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kube-auth
                  key: token
