apiVersion: v1
kind: Service
metadata:
  name: tekton-pipeline-api
  namespace: tekton-pipelines
spec:
  type: ClusterIP
  selector:
    app: tekton-pipeline-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
