apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: yarn-ci
  namespace: tekton-pipelines
spec:
  description: >-
    Some description
  workspaces:
    - name: git-environment
  params:
    - name: LOG_LEVEL
      description: The level of logs
      default: info
  steps:
    - name: some-first-task
      workingDir: $(workspaces.git-environment.path)
      image: the-image
    - name: success
      image: comworkio/tekton-utils-state-success:latest
      workingDir: $(workspaces.git-environment.path)
      env:
        - name: LOG_LEVEL
          value: $(params.LOG_LEVEL)
        - name: TEKTON_WORKSPACE_PATH
          value: $(workspaces.git-environment.path)
      command: ["/state-success.sh"]
