apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kill-redundant-pipelines
  namespace: tekton-pipelines
spec:
  description: >-
    This task will destroy the binded pvc at the end of the pipeline.
  params:
    - name: gitBranchName
      type: string
      description: the branch name
    - name: projectName
      type: string
      description: project name (prefix of the pipelineruns name)
    - name: buildId
      type: string
      description: build id (suffix of the pipelineruns name) to filter
    - name: destroyPvc
      type: string
      description: destroy the associated pvc (enabled or disabled)
      default: enabled
    - name: namespace
      type: string
      description: namespace of tekton pipelines
      default: tekton-pipelines
    - name: logLevel
      type: string
      description: log level
      default: tekton-pipelines
  steps:
    - name: kill-redundant-pipelines
      image: comworkio/tekton-utils-kill-redundant-pipelines:latest
      env:
        - name: GIT_BRANCH
          value: $(params.gitBranchName)
        - name: PROJECT_NAME
          value: $(params.projectName)
        - name: BUILD_ID
          value: $(params.buildId)
        - name: LOG_LEVEL
          value: $(params.logLevel)
        - name: TEKTON_NAMESPACE
          value: $(params.namespace)
        - name: DESTROY_PVC
          value: $(params.destroyPvc)
        - name: KUBE_ENV
          valueFrom:
            secretKeyRef:
              name: kube-auth
              key: env
        - name: KUBE_URL
          valueFrom:
            secretKeyRef:
              name: kube-auth
              key: url
        - name: KUBE_TOKEN
          valueFrom:
            secretKeyRef:
              name: kube-auth
              key: token
      command: ["/kill-redundant-pipelines.sh"]
